name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Packaging Jar
      id: packaging-jar
      shell: bash
      run: mvn -f app clean install
    - name: Build with Maven
      run: mvn -B package -f app
    - name: Publish code coverage
      if: ${{ github.event_name == 'push' }}
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        JACOCO_SOURCE_PATH: ${{github.workspace}}/app/src/main/java
      with:
        coverageCommand: make report
        debug: true
        coverageLocations: ${{github.workspace}}/app/target/site/jacoco/test/jacoco.xml:jacoco
